apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deplyment
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      name: hello-pod
      labels: 
        app: nginx
    spec:
      containers: 
      - name: hello-nginx
        image: nginx:latest
        ports: 
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  namespace: roboshop
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetport: 80
  type: ClusterIP