apiVersion: apps/v1
kind: Deployments
metadata:
  name: hello-deplyment
  namesapce: roboshoop
spec:
  replicas: 1
  selector:
    matcheLables:
      app: nginx
  template:
    metadata: 
      name: hello-pod
      labels: 
        app: nginx
    spec:
      containers: 
      - name: hello-nginx
        image: nginx:latest
        ports: 
        - containerPort: 80

        