apiVersion: v1
kind: Namespace
metadata:
  name: Roboshope
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
provisioner: kubernetes.io/aws-ebs  # For AWS EBS
parameters:
  type: gp2  # General Purpose SSD
reclaimPolicy: Retain  #
---
apiVersion: v1
kind: PresistanceVolume
metadata:
  name: my_ngnix_pv
  namespace: Roboshope
spec:
  capacity:
    storage: 49Gi
  volumeMode: fileSystem 
  accessModes:
    - ReadWriteOnce
  presistanceVolumeClaim: Retain
  storageClassName: gp2
  hostpath:
    path: /data/share

---
apiVersion: v1
kind: PresistanceVolumeClaim
metadata:
  name: my_ngnix_pv
  namespace: Roboshope
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: gp2

---

apiVersion: v1
kind: ConFigMap
metadata:
  name: nginx_config
  namespace: Roboshope
spec:
  data :
    nginx.config: | 
      server {
        listen 80;
        location / {
          root /user/data/share/nginx/html;
          nginx nginx.html nginx.html;
        }
      }
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx_deployment
  namespace: Roboshope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx_pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx_image
          image: naginx:latest
          mountVolumes:
            - name: nginx-path
              mountPath: /user/data/share/nginx/html
              subpath: nginx.config
            - name: nginx-pvc
              mountPath: /data/share/nginx
              
      volumes:
        - name: nginx-path
          congiMap:
            name: nginx_config
        - name: nginx-pvc
          presistanceVolumeClaim:
           claimName: my_ngnix_pv
---
apiVersion: v1
kind: Service
metadata:
  name: nginx_deployment
  namespace: Roboshope
spec:
  selector:
    matchLabels:
      app: nginx
  ports:
    - protocol: tcp
      targetport: 80
      port: 80
  type: LoadBalancer